apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-demo
  template:
    metadata:
      labels:
        app: cicd-demo
    spec:
      containers:
        - name: cicd-demo
          image: vishnu822/cicd-demo:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
